# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f5896390-4e7c-42af-915f-9f700b24c38e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2954-79CA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/media" =
    { device = "/dev/disk/by-uuid/dab9c496-92d6-4a5b-bbdc-7923507717bd";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/da9219dc-ba85-4a39-a1da-e80b563a22a1"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-42443c1919df.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-43364b580aa2.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-67c125e8912f.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-808ab2426c2b.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-9cdd8df5ae63.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-f2bb1e85c141.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth6d28080.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth7039d31.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth8c633f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth90d14d8.useDHCP = lib.mkDefault true;
  # networking.interfaces.vetha924314.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethaebb436.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethb3242fc.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethe21cb34.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.zth6rg6uue.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
